// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RS.Parking.Infrastructure.Migrations
{
    [DbContext(typeof(RSParkingContext))]
    [Migration("20220806165747_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RS.Parking.Domain.Models.AccordType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("id_accord");

                    b.Property<int>("Accord")
                        .HasColumnType("int")
                        .HasColumnName("ie_accord");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bln_active");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_dateCreated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_accord");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("nr_percentage");

                    b.HasKey("Id");

                    b.ToTable("tb_AccordType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Accord = 0,
                            Active = true,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(3423),
                            Description = "PharmaTech",
                            Percentage = 0m
                        },
                        new
                        {
                            Id = (byte)2,
                            Accord = 1,
                            Active = true,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(3426),
                            Description = "Subway",
                            Percentage = 50.0m
                        },
                        new
                        {
                            Id = (byte)3,
                            Accord = 2,
                            Active = true,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(3429),
                            Description = "McDonald's",
                            Percentage = 100m
                        });
                });

            modelBuilder.Entity("RS.Parking.Domain.Models.ControlInOut", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT UNSIGNED")
                        .HasColumnName("id_controlInOut");

                    b.Property<byte>("AccordTypeId")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("cd_accord");

                    b.Property<DateTime>("DateTimeIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_in")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DateTimeOut")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_out");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("ds_licensePlate");

                    b.Property<byte>("VehicleTypeId")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("cd_vehicle");

                    b.HasKey("Id");

                    b.HasIndex("AccordTypeId");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex(new[] { "DateTimeOut" }, "idx_tb_ControleInOut_dt_out");

                    b.ToTable("tb_ControlInOut", (string)null);
                });

            modelBuilder.Entity("RS.Parking.Domain.Models.VehicleType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("id_vehicle");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bln_active");

                    b.Property<decimal>("Cost")
                        .IsConcurrencyToken()
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("vl_cost");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_dateCreated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ds_vehicle");

                    b.HasKey("Id");

                    b.ToTable("tb_VehicleType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)2,
                            Active = true,
                            Cost = 5m,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(6538),
                            Description = "Car 1"
                        },
                        new
                        {
                            Id = (byte)3,
                            Active = true,
                            Cost = 5.5m,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(6540),
                            Description = "Car 2"
                        },
                        new
                        {
                            Id = (byte)4,
                            Active = true,
                            Cost = 3m,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(6542),
                            Description = "Moto 1"
                        },
                        new
                        {
                            Id = (byte)5,
                            Active = true,
                            Cost = 3.5m,
                            DateCreated = new DateTime(2022, 8, 6, 13, 57, 46, 932, DateTimeKind.Local).AddTicks(6543),
                            Description = "Moto 2"
                        });
                });

            modelBuilder.Entity("RS.Parking.Domain.Models.ControlInOut", b =>
                {
                    b.HasOne("RS.Parking.Domain.Models.AccordType", "AccordType")
                        .WithMany()
                        .HasForeignKey("AccordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.Parking.Domain.Models.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccordType");

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
