version: '3.9'
services:

    mariadb:
        image: rs_parking_db:initial
        container_name: RS_Parking_MariaDb
        build:
            context: ./DataBase
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: MyDB@123
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    # api-parking:
    #     image: rs_parking_api:latest
    #     container_name: RS_Parking_API
    #     build:
    #         context: ../
    #         dockerfile: ./Back/src/RS.Parking.API/Dockerfile
    #     restart: always
    #     ports:
    #         - 5000:80
    #         #- 5000:5000
    #         #- 5001:5001
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Production
    #         #- ASPNETCORE_URLS=http://+5000
    #         #- ASPNETCORE_HTTPS_PORT=5000
    #         #- ASPNETCORE_URLS=https://+:5001;http://+5000
    #     depends_on:
    #         - mariadb


    # maria-db:
    #     image: mariadb:latest
    #     #command: --default-authentication-plugin=mysql_native_password
    #     container_name: RS_Parking_MariaDb
    #     restart: always
    #     build:
    #         context: ./DataBase
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - 3306:3306
    #     environment:
    #         MYSQL_ROOT_PASSWORD: MyDB@123
    #     volumes:
    #         - "./DataBase/scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    #         #- "./DataBase/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
